### ISSUE TITLE
Unable to Host the Zettels with GitHub Pages

### ISSUE THREAD

**Issue by athul** [hackstream/zettel#20]
I was trying to host the zettels on my GitHub Pages inside a repo(say 'wiki'), but it seems like the resources doesn't seem to load, it points directly to my base gh pages(<username>.github.io) and not to my gh pages with the repo name(<username.github.io>/wiki). Here is the deployed repo for ref: https://athul.github.io/notes/

**Comment by athul** [comment]
I tried to add a new key in the config file but it seemed to not work everywhere.

I tried it on my fork, https://github.com/athul/zettel/commit/ddb33aaa0fe42f9ef1412508bd2e93d3d0b7d74a

**Comment by iamd3vil** [comment]
Thanks for the bug report @athul I am working on a fix for this.

**Comment by iamd3vil** [comment]
@athul I have released a new version `v0.5.0` with the fix. You can add `site_prefix` in `zettle.toml` as `/wiki` and it should work. Feel free to reopen it if you still face any issue.
