### ISSUE TITLE
Needs support for drafts

### ISSUE THREAD

**Issue by iamd3vil** [hackstream/zettel#8]
We should add support for drafts as well since we might write something which isn't complete yet and can't publish them.

CC: @mr-karan

**Comment by mr-karan** [comment]
@iamd3vil Yep. Sounds doable enough. We can have a meta `draft: true|false`. If `true` we will just skip from our iteration of `posts` for rendering or generating links.

**Comment by iamd3vil** [comment]
Yup. I will send a PR.
